name: deploypipeline

on:
  workflow_dispatch:
    inputs:
      deployCluster:
        description: 'Deploy Cluster Name.'
        required: true
        type: string  
        default: 'EKS'
      secretsName:
        description: 'Secrets Name.'
        type: string
        default: 'acr1'
        
permissions:
  actions: write
env:
  deploymentYamlPath: "${{ github.workspace }}/k8s/application-deployment.yaml" 
  ingressYamlPath: "${{ github.workspace }}/k8s/ingress.yaml"  
  deployFilesPath: "${{ github.workspace }}/k8s"
  k8sNamespace: "hangar"

jobs:
  Deploy_to_EKS:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.deployCluster == 'EKS' }} 
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      
      - name: Set EKS Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.1
        with:
          envFilePath: "./.github/vars/*"
                             
      - name: Deploy app to EKS 
        env:
          imagename: "ultimatom/package_image_test:latest" 
        run: |
          aws eks update-kubeconfig --name ${{ env.cluster_name }} --region 'eu-west-1'
          kubectl get nodes
          .github/workflows/scripts/eks-deploy.sh "${{ env.k8sNamespace }}" "${{ env.imagename }}" "${{ env.dns_name }}" "${{ env.deploymentYamlPath }}" "${{ env.ingressYamlPath }}" "${{ env.deployFilesPath }}"  
        shell: bash
        
      - name: list pods
        run: |
          kubectl get nodes
          kubectl get ns
          kubectl get all -n hangar
          
      - name: Create secrets for EKS
        if: ${{ github.event.inputs.deployCluster == 'EKS' && github.event.inputs.secretsName != '' }}
        env:
          secretsName: "acr1"
        run: |
          aws eks update-kubeconfig --name ${{ env.cluster_name }} --region 'eu-west-1'
          .github/workflows/scripts/ecr-secrets.sh "${{ env.k8sNamespace }}" "${{ env. secretsName }}" "${{ env.aws_access_key }}" "${{ env.aws_secret_access_key }}" "${{ env.registry }}" "${{ env.deploymentYamlPath }}"
        shell: bash



       
          
  
      
